# This workflow will run pytest in the repository directory
# This runs on pull request or on any push to the repository
# based on https://www.youtube.com/watch?v=uFcXrWT4f80
name: Run tests

on:
  pull_request:
    branches: ['main', 'semver2']
  push:
    branches: ['main', 'semver2']
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . # install scratchattach from fs and dependencies
          pip install pytest
          pip install cryptography
          pip install websockets

      - name: Test with pytest
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
        run: |
          pytest tests/
