# This workflow will run pytest in the repository directory
# This runs on pull request or on any push to the repository
# based on https://www.youtube.com/watch?v=uFcXrWT4f80
name: Run tests

on:
  pull_request:
    branches: ['main', 'semver2']
  push:
    branches: ['main', 'semver2']
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - name: install deps
        run: uv sync
      - name: mask secrets
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
        run: |
          cd tests
          uv pip install -e ..
          uv run -m util addmask
          cd ..
      - name: Test with pytest
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
        run: |
          uv run -m pytest tests/
